### ISSUE TITLE
firehose nozzle not recovering from connection issues properly

### ISSUE THREAD

**Issue by antitux** [DataDog/datadog-firehose-nozzle#10]
**Steps to reproduce the issue:**
1. Start datadog firehose nozzle.
2. Either wait for a connection issue, or cause one somehow.
3. Watch the nozzle crash

**Describe the results you received:**
Over the last few weeks, my team has noticed an issue with datadog firehose nozzle instances inside our pcf environment crashing and not properly recovering. Generally we were alerted to the issue because of "No Data" PagerDuty messages going off at 3 in the morning (super fun). We've been able to mitigate the problem by restarting the instances, but the team is getting tired of manually restarting them.

Today, I wrote a bash wrapper to automatically restart the firehose nozzle whenever it crashed. 

During this exercise, I've been monitoring the logs to see what's been causing crashes, and finally was able to capture one. 

```
2017-08-04T13:33:50.303-07:00 [APP/PROC/WEB/0] [OUT] {"timestamp":1501878830.303400517,"process_id":67,"source":"datadog-firehose-nozzle","log_level":"fatal","message":"FATAL ERROR: Post https://app.datadoghq.com/api/v1/series?api_key=XXXXXXXXXXXXXXXXXXXXX: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\n\n","data":null,"file":"/root/go/src/github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle/datadog_firehose_nozzle.go","line":106,"method":"github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle.(*DatadogFirehoseNozzle).postMetrics"}
2017-08-04T13:33:50.305-07:00 [APP/PROC/WEB/0] [ERR] panic: FATAL ERROR: Post https://app.datadoghq.com/api/v1/series?api_key=XXXXXXXXXXXXXXXXXXXXX: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017-08-04T13:33:50.305-07:00 [APP/PROC/WEB/0] [ERR] goroutine 1 [running]:
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] panic(0x7b8b40, 0xc820313db0)
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] github.com/cloudfoundry/gosteno.(*Logger).Log(0xc8200b6840, 0x9059c8, 0x5, 0x1, 0xc8200be180, 0xb1, 0x0)
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /root/go/src/github.com/cloudfoundry/gosteno/logger.go:41 +0x2f0
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /root/go/src/github.com/cloudfoundry/gosteno/logger.go:66 +0x33e
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /root/go/src/github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle/datadog_firehose_nozzle.go:104 +0xfb
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] github.com/cloudfoundry/gosteno.(*BaseLogger).Log(0xc820012400, 0x9059c8, 0x5, 0x1, 0xc8200be180, 0xb1, 0x0)
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] github.com/cloudfoundry/gosteno.(*Logger).Fatalf(0xc8200b6840, 0x950e80, 0x11, 0xc820a4db90, 0x1, 0x1)
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle.(*DatadogFirehoseNozzle).postToDatadog(0xc820a4def8, 0x0, 0x0)
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /root/go/src/github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle/datadog_firehose_nozzle.go:49 +0xd8
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /vagrant/main.go:51 +0x6c0
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /root/go/src/github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle/datadog_firehose_nozzle.go:86 +0x11b
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] main.main()
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] /root/go/src/github.com/cloudfoundry/gosteno/logger.go:164 +0xa6
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle.(*DatadogFirehoseNozzle).postMetrics(0xc820a4def8)
2017-08-04T13:33:50.306-07:00 [APP/PROC/WEB/0] [ERR] github.com/DataDog/datadog-firehose-nozzle/datadogfirehosenozzle.(*DatadogFirehoseNozzle).Start(0xc820a4def8, 0x0, 0x0)
```

**Describe the results you expected:**

If there is a connection issue inside the firehose nozzle, it should gracefully recover, or reattempt the connection, instead of crashing. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Here's the command that we're using to run the application from the binary buildpack inside of a PCF instance:

```
echo "ZZZ starting firehose" && until $HOME/data-dog-nozzle -config ./datadog-firehose-nozzle-$PCF_ENVIRONMENT.json; do echo "ZZZ restarting firehose"; sleep 1 ; done
```

By the way, I totally know that this probably isn't the "recommended deployment behavior" for this application, but the fact that it crashes like this should be something that all users would probably enjoy having mitigated.

**Comment by antitux** [comment]
Anything on this?

**Comment by ahevenor** [comment]
From the details in the log this appears to be just be timing out while attempting to post a metric to datadog.

**Comment by antitux** [comment]
Yep.

But when it times out, it simply dies instead of attempting to reconnect. That's not ideal.

**Comment by ahevenor** [comment]
@gmmeyer was working on a fix for this.

**Comment by gmmeyer** [comment]
In the latest releaes, 64, this is fixed. It was fixed by this PR: https://github.com/DataDog/datadog-firehose-nozzle/pull/13/files/1f45523c37e4cc697c9eba6b3342050b746fb94a#diff-07bcb66e36fc16d3e61b6669735b261bL104

**Comment by gmmeyer** [comment]
If you continue to get these errors, please reopen this ticket. Otherwise, I believe the issue should be resolved here: https://github.com/DataDog/datadog-firehose-nozzle-release/releases/tag/64
